{
    'name': 'Essential Accounting Reports for Odoo 19',
    'version': '1.0.0',
    'category': 'Invoicing',
    'description': 'Essential Report For Odoo Accounting and Other',
    'summary': 'Essential Report For Odoo Accounting and Other',
    'sequence': '1',
    'author': 'Vnzn Tech',
    'license': 'LGPL-3',
    'company': 'Venzn',
    'maintainer': 'Venzn',
    'support': 'vnzntech@gmail.com',
    'website': '',
    'depends': ['account','contacts'],\
    'icon': "/vn_essential_reports/static/description/icon.png",

    'currency':'USD',
    'price': 0.0,
    'data': [
        'security/ir.model.access.csv',
        'data/account_account_type.xml',
        'views/menu.xml',
        'views/ledger_menu.xml',
        'views/financial_report.xml',
        'views/settings.xml',
        'views/account_wizard_views.xml',
        'wizard/account_report_common_view.xml',
        'wizard/partner_ledger.xml',
        'wizard/general_ledger.xml',
        'wizard/trial_balance.xml',
        'wizard/balance_sheet.xml',
        'wizard/profit_and_loss.xml',
        'wizard/tax_report.xml',
        'wizard/aged_partner.xml',
        'wizard/journal_audit.xml',
        'wizard/customer_statement_view.xml',
        'report/report.xml',
        'report/report_partner_ledger.xml',
        'report/report_general_ledger.xml',
        'report/report_trial_balance.xml',
        'report/report_financial.xml',
        'report/report_tax.xml',
        'report/report_aged_partner.xml',
        'report/report_journal_audit.xml',
        'report/report_journal_entries.xml',
        'report/customer_statement_report_pdf.xml',
        'report/account_wizard_reports.xml',
        'report/account_wizard_templates.xml',
    ],
    'pre_init_hook': '_pre_init_clean_m2m_models',
    'images': ['static/description/banner.gif'],
}