from . import diet
from . import res_partner
from . import res_partner
from . import product_product
from . import sale_order
from . import workout
from . import hr_employee
from . import xlsxwritter
from . import account_payments
from . import account_move
from . import floor
from  . import payments