{
    'name' : 'Project',
    'version' : '16.0.0.0',
    'summary': 'Module for fitness management',
    'author': 'Aswin',
    'description': """Module for fitness management""",
    'sequence' : -101,
    'category': 'Health Care',
    'website': 'www.fit.com',
    'depends' : ['base','sale_management','sale','account','hr'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/ir_sequence_data.xml',
        'data/mail_template_for_send_diet.xml',
        'data/mail_template_for_trainers.xml',
        'data/mail_template_inform_regiatration.xml',
        'data/mail_template_for_monthly_report.xml',
        'data/mail_template_for_inform_expiry.xml',
        'data/mail_for_inform_pending_fee.xml',
        'data/cron.xml',
        'wizard/update_wizard_view.xml',
        'wizard/cancel_membership_view.xml',
        'views/diet_view.xml',
        'views/res_partner_view.xml',
        'views/product_product_view.xml',
        'views/workout_view.xml',
        'views/hr_employee_view.xml',
        'views/sale_order_view.xml',
        'views/account_payments_view.xml',
        # 'views/product_template_view.xml',
        'views/account_move_view.xml',
        'views/floor_view.xml',
        'views/menu_view.xml',
        'reports/diet_model_report.xml',
        'reports/workout_model_report.xml',
        'reports/draft_customers_report.xml',
        'reports/report.xml',
        ],
     'license': 'LGPL-3',

}
